### PR TITLE
Bugfix for cache handling

### PR DESCRIPTION
**Pull request by udoklein**
Hi tedyapo,

With the first commit "tconv" I wanted to make the conversion time calculation public. The intention is that this can be used to create a none blocking version of readData. Then I noticed that it would require some of the cached parameters. While moving them around I noticed that I had given them different names than the stuff in the header file. Also I noticed that the convertRaw function that you factored out of readData did not fill the cache.
Along a different line I also noticed that the MLX chip does not accept read register commands while burst is active. Thus I followed your idea to cache write commands. I also trigger refill of the cache after things that might change registers as a side effect.

Unfortunately this is not 100% watertight as reset will NOT reset the burst mode flag. I do not want to call exit implicitly because this would change the behaviour of reset.

Since my first cache commit was flawed please review carefully ;)

### CODE REVIEW

**Comment by tedyapo** [comment]
OK, I'll review thoroughly tomorrow.  Attending the orchestra tonight.

**Comment by udoklein** [comment]
I put another thought into the cache handling and now have improved it a little bit more. You might want to review and merge the new commits intead of my previous pull request.

**Comment by tedyapo** [comment]
I am in the middle of reviewing this.  I think I need to add some regression tests to the repo to catch issues.

**Comment by udoklein** [comment]
Hi Ted,

I created a debug helper for my own purposes. It has a somewhat crude interface but it is much better than nothing for testing. Since it calls more or less everything from the library it is at least usable for a smoke test. Maybe you find it useful.

**Comment by tedyapo** [comment]
Thanks for these fixes!  Very good work.

**Comment by udoklein** [comment]
As I said: thanks a lot for providing me a starting point. As you obviously have noticed I created my own version of a MLX90393 library. Without yours this would have taken a lot longer. So I have to thank you :)

**Comment by tedyapo** [comment]
One thing: would you consider releasing your test code for this project
under an MIT license instead?  Ideology aside, it might be nice to have the
whole project licensed consistently.  Ultimately, the decision is yours
though, and it's a very valuable contribution either way.

**Comment by udoklein** [comment]
Hi Ted,

I am sorry, but I think I will decline this request.

This is something for endless discussions. Exluding ideology from this discussion is hard since every single copyright license is in the end also an ideological statement. 
Having to deal with license questions for more than a decade I prefer GPL over MIT for my spare time projects. I prefer GPL for reasons that in the end boil down to more or less the same reasons as Richard Stallmann. 

With regards to "consistent licensing" I do not see why this is a value per se. A lot of stuff if am dealing with includes >10 licenses. If you value single license only then you might change the whole project to GPL or remove the debug helper from the project. Whoever still wants it can have it from my fork which will then have inconsistent licensing. I will not be offended by that.

**Comment by tedyapo** [comment]
I will leave the debug helper code in the repo.  Like I said, it's a valuable addition, and you are certainly entitled to use a license of your choosing. Again, I thank you for your efforts.  It's a much better library because of them.

I will add a small MIT-licensed example, however, since it was removed.

**Pull request merged**
